galaxy_info:
  author: Padmanabhan Kosalaram (@pakosal1)
  description: Configure an existing Mongo DB instance with a running MAS system.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
