galaxy_info:
  author: David Parker (@durera)
  description: Install IBM operator catalogs in the target OCP cluster.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
