---
# Pre-validation mandatory parameter
# -----------------------------------------------------------------------------
- name: "Fail if aws_region is not provided"
  assert:
    that: aws_region is defined and aws_region != ""
    fail_msg: "aws_region property is required"

- name: "Fail if vpc_id is not provided"
  assert:
    that: vpc_id is defined and vpc_id != ""
    fail_msg: "vpc_id property is required"

- name: "Fail if aws_msk_cidr_az1 is not provided"
  assert:
    that: aws_msk_cidr_az1 is defined and aws_msk_cidr_az1 != ""
    fail_msg: "aws_msk_cidr_az1 property is required"

- name: "Fail if aws_msk_cidr_az2 is not provided"
  assert:
    that: aws_msk_cidr_az2 is defined and aws_msk_cidr_az2 != ""
    fail_msg: "aws_msk_cidr_az2 property is required"

- name: "Fail if aws_msk_cidr_az3 is not provided"
  assert:
    that: aws_msk_cidr_az3 is defined and aws_msk_cidr_az3 != ""
    fail_msg: "aws_msk_cidr_az3 property is required"

- name: "Fail if aws_msk_ingress_cidr is not provided"
  assert:
    that: aws_msk_ingress_cidr is defined and aws_msk_ingress_cidr != ""
    fail_msg: "aws_msk_ingress_cidr property is required"

- name: "Fail if aws_msk_egress_cidr is not provided"
  assert:
    that: aws_msk_egress_cidr is defined and aws_msk_egress_cidr != ""
    fail_msg: "aws_msk_egress_cidr property is required"

- name: "Fail if aws_kafka_user_name is not provided"
  assert:
    that: aws_kafka_user_name is defined and aws_kafka_user_name != ""
    fail_msg: "aws_kafka_user_name property is required"
