---

cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

# For already provisioned clusters set token and server to log directly into rather than cluster type (ROKS/Fyre) specific login
ocp_token: "{{ lookup('env', 'OCP_TOKEN') }}"
ocp_server: "{{ lookup('env', 'OCP_SERVER') }}"

# IBM Cloud ROKS API Key - used when cluster_type == "roks"
ibmcloud_endpoint: "{{ lookup('env', 'IBMCLOUD_ENDPOINT') | default('https://cloud.ibm.com', true) }}"
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

# Fyre username/password - used when cluster_type == "quickburn"
fyre_username: "{{ lookup('env', 'FYRE_USERNAME') }}"
fyre_apikey: "{{ lookup('env', 'FYRE_APIKEY') }}"
fyre_site: "{{ lookup('env', 'FYRE_SITE') | default('svl', true) }}"

# Rosa token & cluster-admin password
rosa_token: "{{ lookup('env', 'ROSA_TOKEN') }}"
rosa_cluster_admin_password: "{{ lookup('env', 'ROSA_CLUSTER_ADMIN_PASSWORD') }}"

# What cluster types does this role support
supported_cluster_types:
  - fyre
  - roks
  - rosa
  - in-cluster
  - aws

k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') | default('', True) }}"

# Enable ipv6?
enable_ipv6: "{{ lookup('env', 'ENABLE_IPV6') | default('false', true) | bool }}"
