---
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
  namespace: ibm-common-services
spec:
  services:
    - name: ibm-cert-manager-operator
      spec:
        certManager:
          certManagerCAInjector:
            resources:
              limits:
                cpu: 200m
                memory: 2048Mi
          certManagerController:
            resources:
              limits:
                cpu: 1000m
                memory: 2048Mi
  size: large
