# 1. Configure Kafka
# ---------------------------------------------------------------------------------------------------------------------
- debug:
    msg:
      - "Kafka Provider .................. {{ kafka_provider }}"
      - "Kafka Action .................... {{ kafka_action }}"

- name: Provision or Deprovision Kafka Instance
  include_tasks: "{{ role_path }}/tasks/provider/{{ kafka_provider }}/{{ kafka_action }}.yml"
