galaxy_info:
  author:
    - André Marcelino
  description: Allow to load dbc script files into manage server. It is an workaround for a gap in Manage operator that should be allowing us to perform this kind of activity.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies: []
