# Create IBM Cloud resource key for EventStreams (service id and apikey will be created automatically)

# First, we will check if the target k8s Secret eventstreams_credentials_secret_name already exists
# If it already exists, the creation of resource key and k8s secret will be skipped
- name: "Debug information"
  debug:
    msg:
      - "Event Streams Service Credentials Name ....... {{ eventstreams_credentials_secret_name }}"

- name: Set ES Resource Id
  set_fact:
    es_id: "{{ es_exist_info.resource.id }}"

- name: Create IBM Cloud resource key for eventstreams (service id and apikey will be created automatically)
  ibm.cloudcollection.ibm_resource_key:
    name: "key-{{ eventstreams_credentials_secret_name }}"
    resource_instance_id: "{{ es_id }}"
    role: "Manager"
    tags:
      - "{{ eventstreams_name }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey }}"
  register: resource_key_info

- name: Fail if apikey not created
  assert:
    that:
      - resource_key_info is defined and resource_key_info != ''
      - resource_key_info.resource is defined and resource_key_info.resource != ''
      - resource_key_info.resource.credentials.api_key is defined and resource_key_info.resource.credentials.api_key != ''
