galaxy_info:
  author: David Parker (@durera)
  description: Install one or more services for IBM CloudPak for Data in support of IBM Maximo Application Suite
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - cp4d

dependencies:
  - role: ibm.mas_devops.ansible_version_check
