---
# Deleting the namespace should be sufficient as long as all the required uninstalls have already been executed
# For example this should always run after the cert_manager role's uninstall if IBM Certificate Manager
# is installed, and after uds role's uninstall action if IBM User Data Services is installed.

# NamespaceScope CRs get stuck on their finalizer
# because the IBM NamespaceScope Operator gets deleted first
# blocking the removal of the ibm-common-services namespace
- name: Get all NamespaceScopes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: NamespaceScope
    namespace: ibm-common-services
  register: ns_scopes_lookup

- name: Delete all NamespaceScopes
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: NamespaceScope
    namespace: ibm-common-services
    name: "{{ item.metadata.name }}"
  loop: "{{ ns_scopes_lookup.resources }}"

- name: Delete the ibm-common-services namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: ibm-common-services
    wait: true
    wait_timeout: 600 # 10 minutes
