---
ocp_node_name: "{{ lookup('env', 'OCP_NODE_NAME') }}"
ocp_node_index: "{{ lookup('env', 'OCP_NODE_INDEX') }}"

ocp_node_label_keys: "{{ lookup('env', 'OCP_NODE_LABEL_KEYS') }}"
ocp_node_label_values: "{{ lookup('env', 'OCP_NODE_LABEL_VALUES') }}"

ocp_node_taint_keys: "{{ lookup('env', 'OCP_NODE_TAINT_KEYS') }}"
ocp_node_taint_values: "{{ lookup('env', 'OCP_NODE_TAINT_VALUES') }}"
ocp_node_taint_effects: "{{ lookup('env', 'OCP_NODE_TAINT_EFFECTS') }}"
