---
mas_upgrade_dryrun: "{{ lookup('env', 'MAS_UPGRADE_DRYRUN') | default('False', True) | bool }}"

mas_channel: "{{ lookup('env', 'MAS_CHANNEL') }}"

mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

skip_compatibility_check: "{{ lookup('env', 'SKIP_COMPATIBILITY_CHECK') | default('False', True) | bool }}"
