apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: rook-ceph-rgw
    ceph_daemon_id: object
    rgw: object
    rook_cluster: openshift-storage
    rook_object_store: object
  name: rgw
  namespace: openshift-storage
spec:
  host: "{{ cos_domain }}"
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: rook-ceph-rgw-object
    weight: 100
  wildcardPolicy: None
