---
#jdbc configuration
db_instance_id: "{{ lookup('env', 'DB_INSTANCE_ID') | default('dbinst', True) }}"
db_username: "{{ lookup('env', 'MAS_JDBC_USER') }}"
jdbc_instance_password: "{{ lookup('env', 'MAS_JDBC_PASSWORD') }}"
jdbc_url: "{{ lookup('env', 'MAS_JDBC_URL') }}"
db_pem_file: "{{ lookup('env', 'MAS_JDBC_CERT_LOCAL_FILE') }}"
# MAS instance configuration
mas_config_scope: "{{ lookup('env', 'MAS_CONFIG_SCOPE')}}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
mas_application_id: "{{ lookup('env', 'MAS_APP_ID') }}"
ssl_enabled: "{{ lookup('env', 'SSL_ENABLED') | bool }}"

# Custom Labels
# -----------------------------------------------------------------------------
custom_labels: "{{ lookup('env', 'CUSTOM_LABELS') | default(None, true) | string | ibm.mas_devops.string2dict() }}"
