---
# AWS Route53 Integration
# -----------------------------------------------------------------------------
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
route53_hosted_zone_name: "{{ lookup('env', 'ROUTE53_HOSTED_ZONE_NAME') }}"
route53_caller_reference: "{{ lookup('env', 'ROUTE53_CALLER_REFERENCE') | default(ansible_date_time.iso8601_basic_short, true) }}" # sample default: "20170930T132646"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-2', True) }}"
route53_hosted_zone_region: "{{ lookup('env', 'ROUTE53_HOSTED_ZONE_REGION') | default(aws_region, True) }}"
route53_policy_name: "allow-route53-change-recordsets-policy"
