---
key_rotation_type:
  roks:
    provider: roks
  rosa:
    provider: aws
  ipi:
    provider: aws

#
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE') }}"
ipi_platform: "{{ lookup('env', 'IPI_PLATFORM')  | default('aws', true)  }}"

# ROKS
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_keyname: "{{ lookup('env', 'IBMCLOUD_KEYNAME') }}"
ibmcloud_output_keydir: "{{ lookup('env', 'IBMCLOUD_OUTPUT_KEYDIR') | default('/tmp', true) }}"

# AWS
# -----------------------------------------------------------------------------
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', True) }}"
aws_username: "{{ lookup('env', 'AWS_USERNAME') }}"
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
