galaxy_info:
  author: Ashish Mahawal
  description: Provision or deprovision  cloud internet services (cis) on ibmcloud
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
