galaxy_info:
  author: André Marcelino (@andrercm)
  description: Creates an AWS access point and associates it with the specified S3 bucket in the targeted AWS account.

  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
