galaxy_info:
  author: David Parker (@durera)
  description: Deploy Kafka cluster configured for IBM Maximo Application Suite (Using Red Hat AMQStreams operator)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - amqstreams
    - kafka

dependencies:
  - role: ibm.mas_devops.ansible_version_check
