---
- hosts: localhost
  any_errors_fatal: true

  pre_tasks:
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MIRROR_MODE') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.mirror_ocp
