---
- hosts: localhost
  vars:
    cluster_type: ipi
    ipi_platform: aws

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'CLUSTER_NAME') != ""
          - lookup('env', 'AWS_ACCESS_KEY_ID') != ""
          - lookup('env', 'AWS_SECRET_ACCESS_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.ocp_deprovision
