---
- hosts: localhost
  vars:
    cluster_type: roks

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'IBMCLOUD_APIKEY') != ""
          - lookup('env', 'CLUSTER_NAME') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.ocp_deprovision
