---
# IBM SLS 3.5.0 Bad Digest Hack
# -----------------------------------------------------------------------------
# The SLS CASE bundle for 3.5.0 has the wrong image digest in it ... not really sure why TBH

- template:
    src: iot860fix/direct.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/direct/{{ case_name }}_{{ case_version }}.txt"

- template:
    src: iot860fix/to-filesystem.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/to-filesystem/{{ case_name }}_{{ case_version }}.txt"

- template:
    src: iot860fix/from-filesystem.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/from-filesystem/{{ case_name }}_{{ case_version }}.txt"
