---
# IBM IOT 8.6.7 Bad Digest Hack
# -----------------------------------------------------------------------------
# The IOT CASE bundle for 8.6.7 has the wrong image digest in it ... not really sure why TBH

- template:
    src: iot867fix/direct.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/direct/{{ case_name }}_{{ case_version }}.txt"

- template:
    src: iot867fix/to-filesystem.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/to-filesystem/{{ case_name }}_{{ case_version }}.txt"

- template:
    src: iot867fix/from-filesystem.txt.j2
    dest: "{{ mirror_working_dir }}/manifests/from-filesystem/{{ case_name }}_{{ case_version }}.txt"
