galaxy_info:
  author: André Marcelino (@andrercm)
  description: Create a new public Hosted Zone in AWS Route53 for domain management.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - dns

dependencies:
  - role: ibm.mas_devops.ansible_version_check
