galaxy_info:
  author: David Parker (@durera)
  description: Increase the size of the volume used by the OCP cluster.  Note that this role is specifically for IBM Cloud ROKS.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - roks

dependencies:
  - role: ibm.mas_devops.ansible_version_check
