---
extra_images:
  - name: cpopen/ibm-maximo-operator-catalog
    registry: "{{ (artifactory_username is defined and artifactory_username != '' and artifactory_token is defined and artifactory_token != '') | ternary( artifactory_image_repo, 'icr.io') }}"
    tag: "{{ catalog_tag }}"
    digest: "{{ catalog_digest }}"
