---
# 1. Failure conditions
# -----------------------------------------------------------------------------
- name: "sendgrid : Fail if required properties are not provided"
  assert:
    that:
      - smtp_type is defined and smtp_type != "" and smtp_type is in supported_smtp_types
      - mas_instance_id is defined and mas_instance_id != ""
      - mas_config_dir is defined and mas_config_dir != ""
    fail_msg: "Missing required properties"

# 2. Debug information
# -----------------------------------------------------------------------------
- name: Debug Information
  debug:
    msg:
      - "SMTP Type .............................. {{ smtp_type }}"
      - "MAS Instance Id ........................ {{ mas_instance_id }}"
      - "MAS Config Dir ......................... {{ mas_config_dir }}"

# 2. Load PodTemplates configuration
# -----------------------------------------------------------------------------
- name: "Load podTemplates configuration"
  include_tasks: "{{ role_path }}/../../common_tasks/pod_templates/main.yml"
  vars:
    config_files: ["ibm-mas-smtpcfg.yml"]

# 3. Execute provider specific tasks
# -----------------------------------------------------------------------------
- include_tasks: tasks/providers/{{ smtp_type }}.yml
