---
# 1. Lookup DB2 namespace
# -------------------------------------------------------------------------
- name: "Lookup Namespace: {{ db2_namespace }}"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ db2_namespace }}"
  register: _db2_namespace_lookup

- name: Set found_db2_namespace Fact
  ansible.builtin.set_fact:
    found_db2_namespace: "{{ _db2_namespace_lookup.resources | length == 1 | default(false, true) }}"

- name: "Namespace Not Found: {{ db2_namespace }}"
  ansible.builtin.debug:
    msg: "Done/Success. There was nothing to update for Db2."
  when:
    - not found_db2_namespace

# If DB2 namespace exists, then we prepare for the upgrade
- include_tasks: "tasks/upgrade/prepare-db2-upgrade.yml"
  when: found_db2_namespace
