---
mas_upgrade_dryrun: "{{ lookup('env', 'MAS_UPGRADE_DRYRUN') | default('False', True) | bool }}"

mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') }}"
mas_app_namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
mas_app_fqn: "ibm-mas-{{ mas_app_id }}"

skip_compatibility_check: "{{ lookup('env', 'SKIP_COMPATIBILITY_CHECK') | default('False', True) | bool }}"
