---

- name: "groups : Create OAuth Groups"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/group.yaml') }}"

- debug: var=groups_cluster_rolebindings

- name: "groups : Create OAuth Groups"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/clusterrolebinding.yaml') }}"
  loop: "{{groups_cluster_rolebindings}}"
  loop_control:
    loop_var: cluster_role
