---
# Default application spec for Predict
mas_appws_spec:
  bindings:
    jdbc: "{{ mas_appws_bindings_jdbc | default( 'system' , true) }}"
    watsonstudio: system
  settings:
    watsonstudio:
      projectid: "{{ cpd_wsl_project_id }}"
    wml:
      instance_id: "{{ cpd_wml_instance_id }}"
      url: "{{ cpd_wml_url }}"
      version: "{{ cpd_product_version.split('.')[0] }}.{{ cpd_product_version.split('.')[1] }}"
    deployment:
      size: "{{ mas_appws_settings_deployment_size }}"
