---
# Application specific variables for Assist
mas_app_fqn: assistapps.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: AssistApp
mas_app_install_delay: 120
mas_app_install_retries: 20
