---
# Application specific variables for Maximo Scheduler Optimization (MSO)
mas_app_fqn: msoapps.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: MSOApp
mas_app_install_delay: 120
mas_app_install_retries: 30
