---
# Application specific variables for Predict
mas_app_fqn: predictapps.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: PredictApp
mas_app_install_delay: 120
mas_app_install_retries: 30

mas_app_settings_predict_deployment_size: "{{ lookup('env', 'PREDICT_DEPLOYMENT_SIZE') | default('small', true) }}"
