---
# Application specific variables for Safety
mas_app_fqn: safetys.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: Safety
mas_app_install_delay: 120
mas_app_install_retries: 30
