---
# Application specific variables for Visual Inspection
mas_app_fqn: visualinspectionapps.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: VisualInspectionApp

mas_app_install_delay: 120
mas_app_install_retries: 30
