---
# The following MAS information is needed to lookup the right Manage app instance
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
manage_workspace_cr_name: "{{ lookup('env', 'MANAGE_WORKSPACE_CR_NAME') }}"

# Default BIM mount path
# ---------------------------------------------------------------------------------------------------------------------
# we'll check if report bundle server is already setup, if it's not then we'll use this property to define the bundle name and its corresponding route
manage_report_bundle_server_name: "{{ lookup('env', 'MANAGE_REPORT_BUNDLE_SERVER_NAME') | default('rpt', true) }}"
