---
# The following MAS information is needed to lookup the right Manage app instance
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

manage_workspace_cr_name: "{{ lookup('env', 'MANAGE_WORKSPACE_CR_NAME') }}"
manage_certificates_file_path_local: "{{ lookup('env', 'MANAGE_CERTIFICATES_FILE_PATH_LOCAL') }}"
manage_certificates_alias_prefix: "" # used internally - initializing it.
