---
# Ouput Directory
# -----------------------------------------------------------------------------
output_dir: "{{ lookup('env', 'OUTPUT_DIR') | default('.', true)}}"

# Service Key Details
# -----------------------------------------------------------------------------
service_instance: "{{ lookup('env', 'SERVICE_INSTANCE')}}"
service_resource_key_name: "{{ lookup('env', 'SERVICE_RESOURCE_KEY_NAME')}}"

# Additional Functions
# -----------------------------------------------------------------------------
delete_service_key: "{{ lookup('env', 'DELETE_SERVICE_KEY')| default('False', true)}}"
output_service_key_details_to_file: "{{ lookup('env', 'OUTPUT_SERVICE_KEY_DETAILS_TO_FILE')| default('False', true)}}"
