galaxy_info:
  author: David Parker (@durera)
  description: Modify Db2 configuration for compatability with Maximo Manage
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - db2

dependencies:
  - role: ibm.mas_devops.ansible_version_check
