galaxy_info:
  author: Alexandre Quinteiro (@alequint)
  description: Verify an installation of IBM Maximo Application Suite application in the target RHOCP cluster
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
