galaxy_info:
  author: Yuvraj Vansure
  description: Deploy User Data Services configured for IBM Maximo Application Suite

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - dro

dependencies:
  - role: ibm.mas_devops.ansible_version_check
