---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "{{ storage_operator }}-operator"
  namespace: openshift-storage
spec:
  channel: "{{ storage_operator_channel }}"
  installPlanApproval: Automatic
  name: "{{ storage_operator }}-operator"
  source: "{{ storage_operator_source }}"
  sourceNamespace: "{{ storage_operator_source_namespace }}"
