---
#vars for ibmcloud
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
master_ibmcloud_api_key: "{{ lookup('env', 'MASTER_IBMCLOUD_APIKEY') }}"
ibmcloud_region: "{{ lookup('env', 'IBMCLOUD_REGION') | default('us-east', True) }}"
master_cis_resource_group: "{{ lookup('env', 'MASTER_CIS_RESOURCE_GROUP') | default('manager', True) }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"
default_master_cis_resource_name: "{{ mas_instance_id }}-cis"
master_cis_resource_name: "{{ lookup('env', 'MASTER_CIS_RESOURCE_NAME') | default(default_master_cis_resource_name, True)}}"
#vars for CIS provision
cis_action: "{{ lookup('env', 'CIS_ACTION') | default('provision', True) }}"
master_cis_base_domain: "{{ lookup('env', 'MASTER_CIS_BASE_DOMAIN') }}"
cis_plan: "{{ lookup('env', 'CIS_PLAN') | default('standard', True) }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
