galaxy_info:
  author: David Parker (@durera)
  description: Deploy MongoDb instance configured for IBM Maximo Application Suite (using Mongo Community Edition operator)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - mongodb

dependencies:
  - role: ibm.mas_devops.ansible_version_check
