galaxy_info:
  author: Caroline Azadze (@caroazad)
  description: Deploy NVIDIA GPU and Node Feature Discoveries Operators needed for Maximo Visual Inspection App
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - gpu

dependencies:
  - role: ibm.mas_devops.ansible_version_check
