---
# 1. Create DocumentDB Instance in given Cluster
# -----------------------------------------------------------------------------
- name: Set Fact for DocumentDB Instance
  set_fact:
    # docdb_instance_identifier is configurable via docdb_instance_identifier_prefix
    docdb_instance_identifier: "{{ docdb_instance_identifier_prefix }}-{{ item }}"
    docdb_instance_exists: false

# check will not fail if Error Code is DBInstanceNotFound or return code is 0
- name: Check if DocDB Instance already exists
  command: >
    aws docdb describe-db-instances \
    --db-instance-identifier '{{ docdb_instance_identifier }}' \
    --filters "Name=db-cluster-id,Values={{docdb_cluster_arn}}"
  register: docdb_cluster_intance_exists_info
  failed_when: docdb_cluster_intance_exists_info.rc not in [0] and ('DBInstanceNotFound' not in docdb_cluster_intance_exists_info.stderr)

- name: Set Fact if DocDB Instance {{ docdb_instance_identifier }} already exists
  when: not docdb_cluster_intance_exists_info.stderr
  set_fact:
    docdb_instance_exists: "{{ docdb_cluster_intance_exists_info.stdout | from_json | json_query('DBInstances[0].DBInstanceIdentifier') == docdb_instance_identifier }}"

- name: Create DocumentDB Cluster Instance
  when: not docdb_instance_exists
  command: >
    aws docdb create-db-instance \
    --db-cluster-identifier '{{ docdb_cluster_name }}' \
    --db-instance-class '{{ docdb_instance_class }}' \
    --db-instance-identifier '{{ docdb_instance_identifier }}' \
    --engine docdb

- name: Fetch DocDb Instance {{ docdb_instance_identifier }}  Info
  when: not docdb_instance_exists
  command: >
    aws docdb describe-db-instances \
      --db-instance-identifier '{{ docdb_instance_identifier }}'
  register: docdb_cluster_intance_create_info
  until:
    - docdb_cluster_intance_create_info is defined
    - docdb_cluster_intance_create_info.stdout is defined
    - docdb_cluster_intance_create_info.stdout | from_json | json_query('DBInstances[0].Endpoint')
    - docdb_cluster_intance_create_info.stdout | from_json | json_query('DBInstances[0].Endpoint.Address')
  retries: 15
  delay: 60 # seconds

- set_fact:
    docdb_cluster_intance_info: "{{ docdb_cluster_intance_exists_info if docdb_instance_exists else docdb_cluster_intance_create_info }}"

- name: Set Fact, DocDB Instance Hosts
  set_fact:
    docdb_replicas: "{{ docdb_replicas|default([]) + [ docdb_cluster_intance_info.stdout | from_json | json_query('DBInstances[0].Endpoint.Address')] }}"

- name: Debug ,DocumentDB Cluster Instance {{ docdb_instance_identifier }} info
  debug:
    msg:
      - "DocumentDB cluster instance ............ {{ docdb_cluster_intance_info }}"
