---
# Authenticate to CP4D (get Bearer token) via REST API
- name: Lookup for generic-preferences CM to determine Version
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: generic-preferences
    namespace: "{{cp4d_namespace}}"
  register: _cpd_generic_preferences

- name: Set CPD Version
  set_fact:
    cpd_version: "{{_cpd_generic_preferences.resources[0].metadata.labels.icpdata_addon_version}}"

- name: Authenticate to CP4D (get Bearer token) via REST API
  block:
    - include_tasks: get-cp4d-route.yml
    - include_tasks: get-cp4d-bearer-token.yml
