---
# Default application spec for IoT
_settings_messagesight:
  storage:
    class: "{{ mas_app_settings_iot_mqttbroker_pvc_storage_class | default('', true) }}"
    size: "{{ mas_app_settings_iot_mqttbroker_pvc_size }}"

_settings_fpl:
  functionsexecutor:
    storage:
      class: "{{ mas_app_settings_iot_fpl_pvc_storage_class | default('', true) }}"
      size: "{{ mas_app_settings_iot_fpl_executor_pvc_size }}"
  pipelinerouter:
    storage:
      class: "{{ mas_app_settings_iot_fpl_pvc_storage_class | default('', true) }}"
      size: "{{ mas_app_settings_iot_fpl_router_pvc_size }}"

# Default IoT spec
mas_app_spec:
  bindings:
    jdbc: "{{ mas_app_bindings_jdbc }}"
    mongo: system
    kafka: system
  components: "{{ ((mas_app_components_iot is defined) and (mas_app_components_iot | length != 0)) | ternary(mas_app_components_iot, {}) }}"
  podTemplates: "{{ ((ibm_mas_iot_iot_pod_templates is defined) and (ibm_mas_iot_iot_pod_templates | length != 0)) | ternary(ibm_mas_iot_iot_pod_templates, []) }}"
  settings:
    deployment:
      size: "{{ mas_app_settings_iot_deployment_size }}"
    messagesight: "{{ _settings_messagesight }}"
    fpl: "{{ _settings_fpl }}"
