---
# Default application specs for Predict
mas_app_spec:
  bindings:
    jdbc: "{{ mas_app_bindings_jdbc }}"
  components: {}
  settings:
    deployment:
      size: "{{ mas_app_settings_predict_deployment_size}}"
  displayName: Predict Workspace
