galaxy_info:
  author: David Parker (@durera)
  description: Upgrade an existing IBM Maximo Application Suite v8.6 installation to v8.7
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - upgrade

dependencies:
  - role: ibm.mas_devops.ansible_version_check
