---
aws_access_point_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-2', True) }}"
aws_access_point_bucket_name: "{{ lookup('env', 'COS_BUCKET_NAME') }}"
aws_access_point_name: "{{ lookup('env', 'AWS_ACCESS_POINT_NAME') | default('access-point-c1', True) }}"
aws_access_point_username: "{{ lookup('env', 'AWS_ACCESS_POINT_USERNAME') }}"
aws_access_point_policy_actions:
  - "s3:GetObject"
  - "s3:ListBucket"
