galaxy_info:
  author: Jonah Luckett (@jonah)
  description: Update the password on an existing cp4d instance
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - cp4d

dependencies:
  - role: ibm.mas_devops.ansible_version_check
