galaxy_info:
  author: David Parker (@durera)
  description: Add labels and taints to a specified node.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - ocp

dependencies: []
