galaxy_info:
  author: Ben Bakowski (@bakowski)
  description: Deploy Kubeturbo

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - kubeturbo

dependencies:
  - role: ibm.mas_devops.ansible_version_check
