galaxy_info:
  author: Andre Marcelino (@andrercm)
  description: Internal-use role that all other roles in the collection declare a dependency upon to ensure that the minimum supported level of Ansible is used.

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops

dependencies: []
