---
apiVersion: uds.ibm.com/v1
kind: AnalyticsProxy
metadata:
  name: analyticsproxy
  namespace: ibm-common-services
spec:
  license:
    accept: true
  image_pull_secret: uds-images-pull-secret

  allowed_domains: '*'

  env_type: lite
  airgappeddeployment:
    enabled: {{ airgap_install }}

  storage_class: "{{ uds_storage_class }}"

  db_archive:
    frequency: '@monthly'
    persistent_storage:
      storage_size: 10G
    retention_age: 6

  event_scheduler_frequency: "{{ uds_event_scheduler_frequency }}"

  kafka:
    storage_size: 5G
    zookeeper_storage_size: 5G

  postgres:
    backup_frequency: '@daily'
    backup_type: incremental
    storage_size: 10G

  tls:
    airgap_host: ''
    uds_host: ''

  ibmproxyurl: 'https://iaps.ibm.com'
  proxy_settings:
    http_proxy: ''
    https_proxy: ''
    no_proxy: ''
