---
mas_rollback_dryrun: "{{ lookup('env', 'MAS_ROLLBACK_DRYRUN') | default('False', True) | bool }}"

mas_core_version: "{{ lookup('env', 'MAS_CORE_VERSION') }}"
rollback_mas_core: "{{ lookup('env', 'ROLLBACK_MAS_CORE') | default('True', True) | bool }}"
verify_core_version: "{{ lookup('env', 'VERIFY_CORE_VERSION') | default('False', True) | bool }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

# SKIP_COMPATIBILITY_CHECK environment is meant only for development. In dev mode, it is set to 'True' to avoid check against supported versions
# In dev mode (SKIP_COMPATIBILITY_CHECK=True), rollback request is accepted from one pre built version to another on the same base version though it is not listed under supported versions. For ex: 8.11.0-pre.dev to 8.11.0-pre.stable.
skip_compatibility_check: "{{ lookup('env', 'SKIP_COMPATIBILITY_CHECK') | default('False', True) | bool }}"
