---
# 1. Report intention
# -----------------------------------------------------------------------------
- name: "install-suds : UDS Deployment details"
  debug:
    msg: "Configuring for SUDS deploy"

# 2. Load PodTemplates configuration
# -----------------------------------------------------------------------------
- name: "Load podTemplates configuration"
  include_tasks: "{{ role_path }}/../../common_tasks/pod_templates/main.yml"
  vars:
    config_files: ["ibm-mas-bascfg.yml"]

# 3. Generate BASCfg for MAS
# All we need to do is create the relevant config, the BASCfg entity manager will
# install SUDS as a result.
# Note that the MAS config resource still refers to UDS by its
# original name (BAS).
# -----------------------------------------------------------------------------
- name: "install-suds : Copy SUDS BASCfg to filesystem"
  ansible.builtin.template:
    src: bascfg-suds.yml.j2
    dest: "{{ mas_config_dir }}/uds.yml"
    mode: '664'
  when: mas_instance_id is defined
