---
mas_rollback_dryrun: "{{ lookup('env', 'MAS_ROLLBACK_DRYRUN') | default('False', True) | bool }}"
rollback_mas_app: "{{ lookup('env', 'ROLLBACK_MAS_APP') | default('True', True) | bool }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
mas_app_namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
mas_app_version: "{{ lookup('env', 'MAS_APP_VERSION') }}"
verify_app_version: "{{ lookup('env', 'VERIFY_APP_VERSION') | default('False', True) | bool }}"

mas_app_fqn: "ibm-mas-{{ mas_app_id }}"

skip_compatibility_check: "{{ lookup('env', 'SKIP_COMPATIBILITY_CHECK') | default('False', True) | bool }}"
