---
- name: "cis : running standard cis suite dns"
  include_tasks: tasks/providers/cis/cis_suitedns_basic.yml
  when:
    - not cis_enhanced_security

- name: "cis : running cis suite dns with enhanced security"
  include_tasks: tasks/providers/cis/cis_suitedns_enhanced.yml
  when:
    - cis_enhanced_security

- include_tasks: tasks/providers/cis/cis_webhook.yml
