---
# Configuration Settings
# -----------------------------------------------------------------------------
ocp_ingress_update_timeouts: "{{ lookup('env', 'OCP_INGRESS_UPDATE_TIMEOUTS') | default('False', true) | bool }}"
ocp_update_ciphers_for_semeru: "{{ lookup('env', 'OCP_UPDATE_CIPHERS_FOR_SEMERU') | default('False', true) | bool }}"


# Ingress Controller Settings
# -----------------------------------------------------------------------------
ocp_ingress_client_timeout: "{{ lookup('env', 'OCP_INGRESS_CLIENT_TIMEOUT') | default('30s', true) }}"
ocp_ingress_server_timeout: "{{ lookup('env', 'OCP_INGRESS_SERVER_TIMEOUT') | default('30s', true) }}"


# Ingress Controller Settings
# -----------------------------------------------------------------------------
ocp_operatorhub_disable_redhat_sources: "{{ lookup('env', 'OCP_OPERATORHUB_DISABLE_REDHAT_SOURCES') | default('False', true) | bool }}"
