galaxy_info:
  author: Rick Acree (@racree)
  description: Generate smtp configuration file for IBM Maximo Application Suite
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - smtp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
