---
# What smtp types does this role support
supported_smtp_types:
  - sendgrid

# smtp_type has no default, it must be passed in
smtp_type: "{{ lookup('env', 'SMTP_TYPE')}}"

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# Custom Labels
custom_labels: "{{ lookup('env', 'CUSTOM_LABELS') | default(None, true) | string | ibm.mas_devops.string2dict() }}"

# sendgrid settings
# =============================================================================
sendgrid_primary_username: "{{ lookup('env', 'SENDGRID_PRIMARY_USERNAME') }}"
sendgrid_primary_email: "{{ lookup('env', 'SENDGRID_PRIMARY_EMAIL') }}"
sendgrid_subuser_email: "{{ lookup('env', 'SENDGRID_SUBUSER_EMAIL') }}"
sendgrid_defaultrecipientemail: "{{ lookup('env', 'SENDGRID_DEFAULTRECIPIENTEMAIL') }}"
sendgrid_ips: "{{ lookup('env', 'SENDGRID_IPS') }}"
sendgrid_primary_apikey: "{{ lookup('env', 'SENDGRID_PRIMARY_APIKEY') }}"

sendgrid_subuser_username_default: "ibm-mas_{{ mas_instance_id }}"
sendgrid_subuser_username: "{{ lookup('env', 'SENDGRID_SUBUSER_USERNAME') | default(sendgrid_subuser_username_default, True) }}"
sendgrid_debug: "{{ lookup('env', 'SENDGRID_DEBUG') | default( False, True) }}"
sendgrid_defaultsendername_default: "''"
sendgrid_defaultsendername: "{{ lookup('env', 'SENDGRID_DEFAULTSENDERNAME') | default( sendgrid_defaultsendername_default, True) }}"
sendgrid_secretname: "{{ mas_instance_id }}-sendgrid-credentials"
sendgrid_configscope: "{{ lookup('env', 'SENDGRID_CONFIGSCOPE') | default('system', True) }}"
sendgrid_hostname: "{{ lookup('env', 'SENDGRID_HOSTNAME') | default('smtp.sendgrid.net', True) }}"
sendgrid_port: "{{ lookup('env', 'SENDGRID_PORT') | default('465', True) }}"
sendgrid_security: "{{ lookup('env', 'SENDGRID_SECURITY') | default('SSL', True) }}"
sendgrid_authentication: "{{ lookup('env', 'SENDGRID_AUTHENTICATION') | default('true', True) }}"
sendgrid_defaultshouldemailpasswords: "{{ lookup('env', 'SENDGRID_DEFAULTSHOULDEMAILPASSWORDS') | default('false', True) }}"
sendgrid_api_url: "{{ lookup('env', 'SENDGRID_API_URL') | default('api.sendgrid.com', True) }}"

# PodTemplates configuration
# mas_pod_templates_dir: path to directory containing podTemplates configuration
# -----------------------------------------------------------------------------
mas_pod_templates_dir: "{{ lookup('env', 'MAS_POD_TEMPLATES_DIR') | default('', true) }}"
