---
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
#vars for aws
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', True) }}"
#vars for vpc
vpc_action: "{{ lookup('env', 'VPC_ACTION') | default('provision', True) }}" #value: provision/deprovision
vpc_cidr: "{{ lookup('env','VPC_CIDR') }}"
vpc_name: "{{ lookup('env','VPC_NAME') }}"
