---
# 1. Debug Info
# -----------------------------------------------------------------------------
- name: "Debug configuration actions"
  debug:
    msg:
      - "ocp_update_ciphers_for_semeru ........... {{ ocp_update_ciphers_for_semeru }}"
      - "ocp_ingress_update_timeouts ............ {{ ocp_ingress_update_timeouts }}"
      - "ocp_operatorhub_disable_redhat_sources . {{ ocp_operatorhub_disable_redhat_sources }}"


# 2. Update API Server
# -----------------------------------------------------------------------------
- include_tasks: update-ciphers-for-semeru.yml
  when: ocp_update_ciphers_for_semeru


# 3. Update Ingress Controller
# -----------------------------------------------------------------------------
- include_tasks: update-ingress-controller.yml
  when: ocp_ingress_update_timeouts


# 4. Update OperatorHub
# -----------------------------------------------------------------------------
- include_tasks: update-operatorhub.yml
  when: ocp_operatorhub_disable_redhat_sources
