galaxy_info:
  author: David Parker (@durera)
  description: Configure DNS entries for IBM Maximo Application Suite (only supports IBM Cloud Internet Services as the DNS provider currently)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - dns

dependencies:
  - role: ibm.mas_devops.ansible_version_check
