---
# MAS configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

manage_workspace_cr_name: "{{ lookup('env', 'MANAGE_WORKSPACE_CR_NAME') }}"

# Default values for SRE team
default_pv_prefix: "{{ mas_instance_id }}-{{ mas_workspace_id }}"
default_sre_pvc_name: "{{ default_pv_prefix }}-cust-files-pvc"
default_sre_mount_path: "/MeaGlobalDirs"

# Manage custom persistent volumes
mas_app_settings_custom_persistent_volume_sc_name: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_PV_STORAGE_CLASS') }}"
mas_app_settings_custom_persistent_volume_pv_name: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_PV_NAME') }}"
mas_app_settings_custom_persistent_volume_pvc_name: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_PVC_NAME') | default(default_sre_pvc_name, true) }}"
mas_app_settings_custom_persistent_volume_pvc_size: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_PVC_SIZE') | default('100Gi', true) }}"
mas_app_settings_custom_persistent_volume_mount_path: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_MOUNT_PATH') | default(default_sre_mount_path, true) }}"

mas_app_settings_custom_persistent_volume_file_path: "{{ lookup('env', 'MAS_APP_SETTINGS_CUSTOM_PV_FILE_PATH') }}"
