---
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"
cp4d_namespace: "{{ lookup('env', 'CP4D_NAMESPACE') | default('ibm-cpd', True) }}"
cp4d_admin_credentials_secret_name: "{{ lookup('env', 'CP4D_ADMIN_CREDENTIALS_SECRET_NAME') | default('admin-user-details', True) }}"
cp4d_admin_username: "{{ lookup('env', 'CP4D_ADMIN_USERNAME') | default('admin', True) }}"
cp4d_admin_password: "{{ lookup('env', 'CP4D_ADMIN_PASSWORD') }}"
cp4d_admin_password_force_update: "{{ lookup('env', 'CP4D_ADMIN_PASSWORD_FORCE_UPDATE') | default('False', True) }}"
