---
# 1. Report intention
# -----------------------------------------------------------------------------
- name: "uninstall-suds : UDS Deployment details"
  debug:
    msg:
      - "Uninstalling SUDS"

# 2. Update BASCfg for MAS
# All we need to do is to set "suds: false" in the relevant config, the BASCfg entity
# manager will uninstall SUDS as a result.
# Note that the MAS config resource still refers to UDS by its
# original name (BAS).
# -----------------------------------------------------------------------------
- name: "uninstall-suds: Update BasCfg CR with SUDS - False"
  kubernetes.core.k8s:
    state: patched
    api_version: config.mas.ibm.com/v1
    kind: BasCfg
    name: "{{ mas_instance_id }}-bas-system"
    namespace: "mas-{{ mas_instance_id }}-core"
    definition:
      spec:
        suds: false
  # Ignore errors if there is no existing BAS Cfg, in which case there will be no SUDS installed
  ignore_errors: yes
