---
# Certificate Manager variables
cert_manager_action: "{{ lookup('env', 'CERT_MANAGER_ACTION') | default('install', true) }}"
cert_manager_provider: "{{ lookup('env', 'CERT_MANAGER_PROVIDER') | default('redhat', true) }}"

cert_manager_defaults:
  redhat:
    channel: "{{ lookup('env', 'REDHAT_CERT_MANAGER_CHANNEL') | default('stable-v1', true) }}"
    operator_namespace: "cert-manager-operator"
    operand_namespace: "cert-manager"
  ibm:
    channel: "Automatically defined by IBM Cloud Pak Foundational Services"
    operator_namespace: "ibm-common-services"
    operand_namespace: "ibm-common-services"

cert_manager_operator_namespace: "{{ cert_manager_defaults[cert_manager_provider].operator_namespace }}"
cert_manager_namespace: "{{ cert_manager_defaults[cert_manager_provider].operand_namespace }}"
cert_manager_channel: "{{ cert_manager_defaults[cert_manager_provider].channel }}"

# Namespace to setup ClusterIssuers when referencing a secret via the secretName field
# ClusterIssuers' secrets will be looked for in the Cluster Resource Namespace defined
# Default value is the namespace where cert-manager is running which is automatically detected (thus default is empty)
# https://cert-manager.io/docs/configuration/
cert_manager_cluster_resource_namespace: ""
