---
# The following MAS information is needed to lookup the right Manage app instance
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
is_prod: "{{ lookup('env', 'IS_PROD') | default('false', true) | bool }}" # True if the bucket for production environment, otherwise false.

# Manage logging provider
# ---------------------------------------------------------------------------------------------------------------------
cos_type: "{{ lookup('env', 'COS_TYPE') }}" # "ibm" or "aws"
cos_type_supported:
  - "ibm"
  - "aws"

cos_cert_alias_prefix: "{{ cos_type }}coscertpart" # prefix to be used to name the cloud object storage certificates

# Manage app DB2 instance where COS configuration will be done
# ---------------------------------------------------------------------------------------------------------------------
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('db2u', true) }}"
db2_instance_name: "{{ lookup('env', 'DB2_INSTANCE_NAME') }}" # e.g. db2u-iot or db2u-manage
db2_dbname: "{{ lookup('env', 'DB2_DBNAME') | default('BLUDB', true) }}"
