---
- name: Fail if vpc_action is not defined
  assert:
    that:
      - vpc_action is defined and vpc_action != ''
    fail_msg: "property vpc_action is required"

# 1. Create or Destroy VPC
# ---------------------------------------------------------
- name: "{{ vpc_action }} VPC on AWS Cloud in Region {{ aws_region }}"
  include_tasks: "{{vpc_action}}.yml"
