---
- name: "Debug CPD certificate details"
  debug:
    msg:
      - "CPD namespace .................. {{ cpd_instance_namespace }}"
      - "CPD cluster issuer name ........ {{ cpd_prod_issuer_name }}"
      - "CPD custom domain .............. cp4d.{{ cpd_custom_domain }}"

- name: "Create certificate to be used for suite cp4d route"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cp4d/cp4d-certificate.yml.j2') }}"
    wait: yes
    wait_timeout: 600 #10 minutes
    wait_condition:
      type: Ready
      status: True

- name: "Lookup suite cp4d route certificate"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "suite-cp4d-certificate"
    namespace: "{{ cpd_instance_namespace }}"
  register: suiteCp4dCrtSecret
  retries: 120 # 5 minutes
  delay: 5 # seconds
  until:
    - suiteCp4dCrtSecret.resources is defined
    - suiteCp4dCrtSecret.resources[0]['data']['tls.crt'] is defined

# Potentially a custom TLS cert might have been setup for the cp4d web client. Look for this first
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=client-using-custom-tls-certificate-connect-platform
- name: "Lookup overridden internal CP4D CA certificate"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "external-tls-secret"
    namespace: "{{ cpd_instance_namespace }}"
  register: cp4dCrtSecret

- name: "Lookup default internal CP4D CA certificate if no external-tls-secret"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "ibm-nginx-internal-tls-ca"
    namespace: "{{ cpd_instance_namespace }}"
  register: cp4dCrtSecret
  when:
    - cp4dCrtSecret.resources | length == 0

- name: "Set CP4D custom route with certificate"
  vars:
    cp4dInternalCertificateAuthorityCertificate: "{{ cp4dCrtSecret.resources[0]['data']['cert.crt'] | b64decode }}"
    suiteCp4dExternalCertificate: "{{ suiteCp4dCrtSecret.resources[0]['data']['tls.crt'] | b64decode }}"
    suiteCp4dExternalKey: "{{ suiteCp4dCrtSecret.resources[0]['data']['tls.key'] | b64decode }}"
    suiteCp4dExternalCertificateAuthorityCertificate: "{{ suiteCp4dCrtSecret.resources[0]['data']['ca.crt']  | default('') }}"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/cp4d/cp4d-route.yml.j2') }}"
  when:
    - cp4dCrtSecret.resources | length > 0 # only create the cp4d route if the cp4d ibm-nginx-internal-tls-ca secret exists
