galaxy_info:
  author: André Marcelino (@andrercm)
  description: Check an existing IBM Maximo Application Suite installation is ready to rollback
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - rollback

dependencies:
  - role: ibm.mas_devops.ansible_version_check
