galaxy_info:
  author: David Parker (@durera)
  description: Deploy IBM Db2 instance configured for IBM Maximo Application Suite
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - db2

dependencies: []
