---
- name: "Import Certificates from Variable: Debug information"
  debug:
    msg:
      - "Manage certificates count to be added ........................... {{ manage_certificates | length }}"
      - "Manage certificates aliases prefix .............................. {{ manage_certificates_alias_prefix }}"

- name: "Assert there's a least one certificate to be added"
  assert:
    that:
      - manage_certificates | length > 0
      - manage_certificates | type_debug == 'list'
      - manage_certificates_alias_prefix is defined and manage_certificates_alias_prefix !=''
    fail_msg: "There should be at least one certificate and alias prefix to be imported."

- name: "Combine new certificates from `manage_certificates` variable into existing Manage certificates"
  set_fact:
    manage_certificates: "{{ existing_manage_imported_certs + manage_certificates }}"
    manage_certificates_aliases: "{{ existing_manage_imported_certs_aliases }}"

# Ensure we only have unique certs to avoid patching duplicates
- set_fact:
    manage_certificates: "{{ manage_certificates | unique | select }}"
