---
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

mas_app_ws_apiversion: "{{ lookup('env', 'MAS_APP_WS_APIVERSION') }}"
mas_app_ws_kind: "{{ lookup('env', 'MAS_APP_WS_KIND') }}"
mas_app_namespace: "{{ lookup('env', 'MAS_APP_NAMESPACE') }}"

# By default, verify every minute up to ten minutes
mas_app_cfg_retries: "{{ lookup('env', 'MAS_APP_CFG_RETRIES') | default(10, True) }}"
mas_app_cfg_delay: "{{ lookup('env', 'MAS_APP_CFG_DELAY') | default(60, True) }}"
