---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "{{ local_storage_operator_channel }}"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: "{{ local_storage_operator_source }}"
  sourceNamespace: "{{ local_storage_operator_source_namespace }}"
