---

- name: "Debug mas_manual_cert_mgmt"
  when: not mas_manual_cert_mgmt
  debug:
    msg: "mas_manual_cert_mgmt is not True, indicating the installation is using cert-manager to create certificates. This role will not take any action"

- name: "Proceed with suite_certs role execution"
  when: mas_manual_cert_mgmt
  include_tasks: tasks/run.yml
