galaxy_info:
  author: Jonah Luckett (@JonahLuckett)
  description: Create IBM Cloud resource keys (apikeys for specific services associated to the account)
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - ibmcloud

dependencies:
  - role: ibm.mas_devops.ansible_version_check
