- name: Verify minimum Ansible version is {{ required_ansible_version }}
  assert:
    that: "ansible_version.full is version_compare(required_ansible_version, '>=')"
    fail_msg: "This collection is only supported on Ansible version {{ required_ansible_version }} or greater, your current Ansible version is {{ ansible_version.full }}"
