galaxy_info:
  author:
    - Paul Stone
    - David Parker
  description: Mirror images to a local registry for AirGap installation
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies: []
