---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{group_name}}-clusterrolebinding"
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "{{group_name}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{cluster_role}}"
