---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
#   tokenConfig:
#     accessTokenInactivityTimeout: 400s
  identityProviders:
    - github:
        clientID: "{{oauth.github_client_id_value}}"
        clientSecret:
          name: "github-client-secret-{{cluster_name}}"
        hostname: "{{oauth.github_hostname}}"
        organizations: {{oauth.organizations}}
        teams: []
      mappingMethod: claim
      name: ibmgithub
      type: GitHub
