---
apiVersion: v1
kind: Secret
metadata:
  name: "github-client-secret-{{cluster_name}}"
  namespace: openshift-config
type: Opaque
stringData:
  clientSecret: "{{oauth.github_client_secret_value}}"
