---

- name: "quickburn : Fail if fyre_user and fyre_apikey are not provided"
  assert:
    that:
      - fyre_username is defined and fyre_username != ""
      - fyre_apikey is defined and fyre_apikey != ""
    fail_msg: "fyre_username & fyre_apikey properties are required"


# 1. Debug Info
# -----------------------------------------------------------------------------
- name: "quickburn : Debug information"
  debug:
    msg:
      - "Cluster name ................. {{ cluster_name }}"
      - "Username ..................... {{ fyre_username }}"
      - "Password ..................... *****************"
      - "Site ......................... {{ fyre_site }}"

# 2. Determine whether cluster exists
# -----------------------------------------------------------------------------
- name: "quickburn : Check if cluster already exists"
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/check_hostname/{{ cluster_name }}?site={{ fyre_site }}"
    user: "{{ fyre_username }}"
    password: "{{ fyre_apikey }}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _cluster_exist
  failed_when: _cluster_exist.status == 403

- name: "fyre : Debug cluster lookup"
  debug:
    var: _cluster_exist

# 3. Deprovision if cluster exists
# -----------------------------------------------------------------------------
- name: "quickburn : Deprovision quick burn cluster"
  when:
    - _cluster_exist.json is defined
    - _cluster_exist.json.owning_user is defined # when there's cluster owner, it means the cluster exists thus we can deprovision it
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/ocp/{{ cluster_name }}?site={{ fyre_site }}"
    user: "{{ fyre_username }}"
    password: "{{ fyre_apikey }}"
    method: DELETE
    status_code:
      - 200
      - 400
    force_basic_auth: yes
    validate_certs: false
