---
# 1. Set uds_tls_crt
# -----------------------------------------------------------------------------
- name: "gencfg : Set uds_tls_crt fact for BasCfg when using existing UDS"
  when:
    - uds_tls_crt is not defined or uds_tls_crt == ""
    - uds_tls_crt_local_file_path is defined and uds_tls_crt_local_file_path != ""
  set_fact:
    uds_tls_crt: "{{ lookup('file', uds_tls_crt_local_file_path) | regex_findall('(-----BEGIN .+?-----(?s).+?-----END .+?-----)', multiline=True, ignorecase=True) }}"
  no_log: true

# Load uds_certs template to dynamically set as many uds certificates as identified
- set_fact:
    uds_certs: "{{ lookup('ansible.builtin.template', 'templates/bas-certs.yml.j2') }}"
  when:
    - uds_tls_crt is defined
    - uds_tls_crt | length > 0

# 2. Check for required facts
# -----------------------------------------------------------------------------
- name: "gencfg : Fail if uds_endpoint_url has not been provided"
  assert:
    that: uds_endpoint_url is defined and uds_endpoint_url|length != 0
    fail_msg: "uds_endpoint_url property has not been set"

- name: "gencfg : Fail if uds_api_key has not been provided"
  assert:
    that: uds_api_key is defined and uds_api_key|length != 0
    fail_msg: "uds_api_key property has not been set"

- name: "gencfg : Fail if uds_tls_crt has not been provided"
  assert:
    that: uds_tls_crt is defined and uds_tls_crt|length != 0
    fail_msg: "uds_tls_crt property has not been set"

# 3. Provide Debug information
# -----------------------------------------------------------------------------
- name: "gencfg : Debug information"
  debug:
    msg:
      - "UDS URL ............................ {{ uds_endpoint_url }}"
      - "UDS Contact First Name ............. {{ uds_contact.first_name | default('<undefined>', True) }}"
      - "UDS Contact Last Name .............. {{ uds_contact.last_name | default('<undefined>', True) }}"
      - "UDS Contact e-mail ................. {{ uds_contact.email | default('<undefined>', True) }}"

# 4. Generate BASCfg for MAS
# -----------------------------------------------------------------------------
- name: "gencfg : Copy BASCfg to filesystem"
  ansible.builtin.template:
    src: bascfg.yml.j2
    dest: "{{ mas_config_dir }}/uds.yml"
    mode: "664"
  when: mas_instance_id is defined
