---
ocp_fips_enabled: "{{ lookup('env', 'OCP_FIPS_ENABLED') | default('false', true) | bool }}"
uds_action: "{{ lookup('env', 'UDS_ACTION') | default('install-suds' if ocp_fips_enabled else 'install', true) }}"

# UDS in-cluster installation
# -----------------------------------------------------------------------------
uds_storage_class: "{{ lookup('env', 'UDS_STORAGE_CLASS') }}"
uds_event_scheduler_frequency: "{{ lookup('env', 'UDS_EVENT_SCHEDULER_FREQUENCY') | default('@daily', true) }}"

# BASCfg generation
# -----------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
mas_segment_key: "{{ lookup('env', 'MAS_SEGMENT_KEY') }}"

uds_contact:
  email: "{{ lookup('env', 'UDS_CONTACT_EMAIL') }}"
  first_name: "{{ lookup('env', 'UDS_CONTACT_FIRSTNAME') }}"
  last_name: "{{ lookup('env', 'UDS_CONTACT_LASTNAME') }}"

# Passthrough Mode (no installation)
# -----------------------------------------------------------------------------
# TODO: Needed for ROSA, but we need to fix this so that we can find the resource another way
cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"

uds_endpoint_url: "{{ lookup('env', 'UDS_ENDPOINT_URL') }}"
uds_tls_crt: "{{ lookup('env', 'UDS_TLS_CERT') }}"
uds_tls_crt_local_file_path: "{{ lookup('env', 'UDS_TLS_CERT_LOCAL_FILE_PATH') }}"
uds_include_isrg_root_cert: "{{ lookup('env', 'UDS_INCLUDE_ISRG_ROOT_CERT') | default('true', true) | bool }}" # mainly needed for IBM Cloud hosted services
uds_api_key: "{{ lookup('env', 'UDS_API_KEY') }}"

# Custom Labels
# -----------------------------------------------------------------------------
custom_labels: "{{ lookup('env', 'CUSTOM_LABELS') | default(None, true) | string | ibm.mas_devops.string2dict() }}"

# PodTemplates configuration
# mas_pod_templates_dir: path to directory containing podTemplates configuration
# -----------------------------------------------------------------------------
mas_pod_templates_dir: "{{ lookup('env', 'MAS_POD_TEMPLATES_DIR') | default('', true) }}"

# dro migration flag
dro_migration: "{{ lookup('env', 'DRO_MIGRATION') | default('', true) }}"
