name: Deploy MAS Core

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible and MAS DevOps Collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install ibm.mas_devops

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MAS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MAS_HOST }} >> ~/.ssh/known_hosts

      - name: Run MAS Core Installation Playbook
        run: |
          ansible-playbook \
            -i ansible/inventory/hosts.yml \
            ansible/playbooks/mas_core_install.yml \
            --extra-vars "ansible_user=${{ secrets.MAS_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa"
