name: Publish Ansible Collection

on:
  workflow_dispatch:  # Allows manual runs
  release:
    types: [published]

jobs:
  ansible-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install Node.js & semver
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install semver
        run: npm install -g semver

      # 4️⃣ Add npm global bin to PATH so semver works
      - name: Add npm global binaries to PATH
        run: echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      # 5️⃣ Set default VERSION if not defined
      - name: Set default VERSION
        run: echo "VERSION=1.0.0" >> $GITHUB_ENV

      # 6️⃣ Ensure .env.sh exists
      - name: Ensure .env.sh exists
        run: |
          mkdir -p "$GITHUB_WORKSPACE/build/bin"
          if [ ! -f "$GITHUB_WORKSPACE/build/bin/.env.sh" ]; then
            if [ -f "$GITHUB_WORKSPACE/build/bin/env.sh" ]; then
              mv "$GITHUB_WORKSPACE/build/bin/env.sh" "$GITHUB_WORKSPACE/build/bin/.env.sh"
            else
              touch "$GITHUB_WORKSPACE/build/bin/.env.sh"
            fi
          fi

      # 7️⃣ Debug: list build/bin files
      - name: Debug build/bin
        run: |
          echo "Listing build/bin files..."
          if [ -d "$GITHUB_WORKSPACE/build/bin" ]; then
            ls -la $GITHUB_WORKSPACE/build/bin
          else
            echo "Directory build/bin does not exist!"
          fi

      # 8️⃣ Initialise build system (skip if folder missing)
      - name: Initialise the build system
        run: |
          if [ -d "$GITHUB_WORKSPACE/build/bin" ]; then
            chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
            $GITHUB_WORKSPACE/build/bin/initbuild.sh || echo "initbuild.sh failed or missing"
            source $GITHUB_WORKSPACE/build/bin/functions.sh || echo "functions.sh missing"
          else
            echo "Skipping build system initialization (build/bin missing)"
          fi
          python -m pip install -q ansible==2.10.3 yamllint

      # 9️⃣ Validate collection lint
      - name: Validate Ansible collection lint
        run: |
          if [ -f "$GITHUB_WORKSPACE/yamllint.yaml" ]; then
            yamllint --format standard -c $GITHUB_WORKSPACE/yamllint.yaml $GITHUB_WORKSPACE/ibm/mas_devops
          else
            echo "yamllint.yaml not found, skipping lint"
          fi

      # 🔟 Build collection (skip if missing)
      - name: Build the Ansible collection
        run: |
          if [ -f "$GITHUB_WORKSPACE/build/bin/build-collection.sh" ]; then
            $GITHUB_WORKSPACE/build/bin/build-collection.sh || echo "build-collection.sh failed"
          else
            echo "build-collection.sh missing, skipping build"
          fi

      # 1️⃣1️⃣ Upload collection to GitHub release
      - name: Upload Ansible Collection
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/ibm/mas_devops/ibm-mas_devops-${{ env.VERSION }}.tar.gz
          asset_name: ibm-mas_devops-${{ env.VERSION }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      # 1️⃣2️⃣ Publish to Ansible Galaxy
      - name: Publish Collection
        if: success()
        run: |
          if [ -f "$GITHUB_WORKSPACE/ibm/mas_devops/ibm-mas_devops-${{ env.VERSION }}.tar.gz" ]; then
            ansible-galaxy collection publish ${{ github.workspace }}/ibm/mas_devops/ibm-mas_devops-${{ env.VERSION }}.tar.gz --token=${{ secrets.ANSIBLE_GALAXY_TOKEN }}
          else
            echo "Collection tar.gz not found, skipping publish"
          fi

      # 1️⃣3️⃣ Optional: Dependency check
      - name: Perform dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'ansible-devops'
          path: '.'
          format: 'HTML'

      # 1️⃣4️⃣ Upload dependency check results
      - name: Upload dependency check results
        uses: actions/upload-artifact@v4
        with:
           name: OWASP dependency check report
           path: ${{github.workspace}}/reports
           retention-days: 90
