galaxy_info:
  author: Ashish Mahawal (@ashish-mahawal1)
  description: Configures MAS Manage with IBM Cloud Eventstreams
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
